apiVersion: 'nais.io/v1alpha1'
kind: Application
metadata:
  name: sdpkanal
  namespace: default
  labels:
    team: "integrasjon"
spec:
  image: "repo.adeo.no:5443/integrasjon/sdpkanal:@@VERSION@@"
  team: integrasjon
  replicas:
    min: 1
    max: 1
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 768Mi
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/virksomhetssertifikat
        kvPath: {{SDP_VIRKSOMHETSSERTIFIKAT_VAULT_PATH}}
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: {{SDP_CREDENTIALS_VAULT_PATH}}
  env:
    - name: MQGATEWAY04_HOSTNAME
      value: {{MQGATEWAY04_HOSTNAME}}
    - name: MQGATEWAY04_PORT
      value: '{{MQGATEWAY04_PORT}}'
    - name: MQGATEWAY04_NAME
      value: {{MQGATEWAY04_NAME}}
    - name: SDP_SEND_STANDARD_QUEUENAME
      value: {{SDP_SEND_STANDARD_QUEUENAME}}
    - name: SDP_SEND_PRIORITERT_QUEUENAME
      value: {{SDP_SEND_PRIORITERT_QUEUENAME}}
    - name: SDP_SEND_STANDARD_BOQ_QUEUENAME
      value: {{SDP_SEND_STANDARD_BOQ_QUEUENAME}}
    - name: SDP_SEND_PRIORITERT_BOQ_QUEUENAME
      value: {{SDP_SEND_PRIORITERT_BOQ_QUEUENAME}}
    - name: SDP_KVITTERING_STANDARD_QUEUENAME
      value: {{SDP_KVITTERING_STANDARD_QUEUENAME}}
    - name: SDP_KVITTERING_PRIORITERT_QUEUENAME
      value: {{SDP_KVITTERING_PRIORITERT_QUEUENAME}}
    - name: SDPKANAL_CHANNEL_NAME
      value: {{SDPKANAL_CHANNEL_NAME}}
    - name: EBMS_MSH_URL
      value: {{EBMS_MSH_URL}}
    - name: NO_NAV_LEGALARCHIVE_URL
      value: {{NO_NAV_LEGALARCHIVE_URL}}
    - name: SDP_CHECK_REVOCATION
      value: {{SDP_CHECK_REVOCATION}}
    - name: NO_NAV_SDPKANAL_SFTP_URL
      value: {{NO_NAV_SDPKANAL_SFTP_URL}}
    - name: NO_NAV_SDPKANAL_DOKUMENT_PATH_PREFIX
      value: {{NO_NAV_SDPKANAL_DOKUMENT_PATH_PREFIX}}
